name: dailymotion

services:
  smtp:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dailymotion
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U user -d dailymotion
      interval: 5s
      retries: 10

  api:
    build: .
    environment:
      DB_URL: postgresql://user:password@db:5432/dailymotion
      API_LOG_LEVEL: INFO
      API_LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      SMTP_HOST: smtp
      SMTP_PORT: 1025
      SMTP_FROM_EMAIL: no-reply@example.com
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      smtp:
        condition: service_started
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')",
        ]
      interval: 5s
      start_period: 10s
      retries: 10
