name: Test API

on:
  push:
    branches:
      - '*'
      # - '!master' uncomment in real life*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --locked --all-groups
      - name: Run tests
        run: uv run pytest tests

# *in real life proper github settings would be used to protect master branch from merging